travis:
  secure:
    BINSTAR_TOKEN: yaw7l+NcBPDY+p8bQygO+o0gsnMlJELIjtbeUSA3dClJcokvocQJpipMacH2MAToEQoAtcGS/llLgWbk4UY534XhiNsfMauKEFYWxv+8abl+kCxEyytXxdDxYyt1PQXZXS5nJbVTX+C1F4T8kWW3YxMZ0gbc00iP+XfGPMvbGfskU+5SPuAbSNxSu9BsEvfh30mrIWTGsJBHr9RLQeEPDYFrtxgjuWs+auHE7fss+bqfCrRNiJlEOsXifpB+LpNQWOoqZZ397qM10MIKkcvaE7zL9R5Ux60pkUUUD6O9T1YPqarFpxEuCLSL8GXJnoYt24uivmvZyTV+r27NaOjUu6DgipQsSvdmeSoogzN46KmjOpdWpvM1H2Kwb5FAjpK6M1U0AZdE+fqh01opNNK54c/Fx3nhA+rfmTER5cjdRKs4uciTjKKiSEtg4A/w/R4jyNmJZy92uzLO+9a1W2ysJ7AQCmxXhh5eHLpw9tbRU5CsghCM7GcrVKxAbZdxLXRGThEC9vdCKndYpMOkO4WzOdY+esdfsOgQcci93ReuB091/69sFYq597aBWot7fkhsIUHv1epPectVuA6yfbRuxRkUytKUmnf3N3FX1hkFYYo/hFc4AtaLn0Vr948V1w62oH42vZ2bJD/ZvD/JlsVac92dAMR+bV0YEhHHkM987qc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
